### ISSUE TITLE
Number format

### ISSUE THREAD

**Issue by franciscocardoso** [miguelmota/is-valid-ssn#1]
Acording to [socialsecurity](https://www.socialsecurity.gov/employer/ssnvshandbk/usingSSNVS.htm#&a0=1) the social security number must be, and I quote,  "... nine (9) numerical characters only. Spaces, alphabetic characters, hyphens, slashes or any other special characters are not allowed".

Would you accept an PR removing the `reWithDash` validation?

**Comment by miguelmota** [comment]
https://github.com/miguelmota/is-valid-ssn/pull/2
